dist: xenial
language: java
sudo: false
jdk: openjdk17
install: true
addons:
  sonarcloud:
    organization: "cleysonph"
    token: $SONAR_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=CleysonPH_personal-expenses-manager
cache:
  directories:
    - $HOME/.m2
